//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.AddCoursesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddCoursesService.IAddCoursesService")]
    public interface IAddCoursesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddCoursesService/addCourse", ReplyAction="http://tempuri.org/IAddCoursesService/addCourseResponse")]
        string addCourse(string Code, string Name, int seats, string Instructer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddCoursesService/addCourse", ReplyAction="http://tempuri.org/IAddCoursesService/addCourseResponse")]
        System.Threading.Tasks.Task<string> addCourseAsync(string Code, string Name, int seats, string Instructer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddCoursesServiceChannel : WebApplication1.AddCoursesService.IAddCoursesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddCoursesServiceClient : System.ServiceModel.ClientBase<WebApplication1.AddCoursesService.IAddCoursesService>, WebApplication1.AddCoursesService.IAddCoursesService {
        
        public AddCoursesServiceClient() {
        }
        
        public AddCoursesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddCoursesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddCoursesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddCoursesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string addCourse(string Code, string Name, int seats, string Instructer) {
            return base.Channel.addCourse(Code, Name, seats, Instructer);
        }
        
        public System.Threading.Tasks.Task<string> addCourseAsync(string Code, string Name, int seats, string Instructer) {
            return base.Channel.addCourseAsync(Code, Name, seats, Instructer);
        }
    }
}
